create table telegram_user
(
    id            bigint generated by default as identity
        primary key,
    telegram_id   bigint                   not null
        unique,
    first_name    text                     not null,
    last_name     text,
    username      text,
    is_bot        boolean                  not null,
    language_code text,
    updated       timestamp with time zone not null,
    created       timestamp with time zone not null
);

create table telegram_chat
(
    id          bigint generated by default as identity
        primary key,
    telegram_id bigint                   not null
        unique,
    title       text,
    type        text                     not null,
    updated     timestamp with time zone not null,
    created     timestamp with time zone not null
);
