create table telegram_user
(
    id            bigint generated by default as identity
        primary key,
    telegram_id   bigint                   not null
        unique,
    first_name    text                     not null,
    last_name     text,
    username      text,
    is_bot        boolean                  not null,
    language_code text,
    updated       timestamp with time zone not null,
    created       timestamp with time zone not null
);

create table telegram_chat
(
    id          bigint generated by default as identity
        primary key,
    telegram_id bigint                   not null
        unique,
    title       text,
    type        text                     not null,
    updated     timestamp with time zone not null,
    created     timestamp with time zone not null
);

create table game
(
    id           bigint generated by default as identity
        primary key,
    name         text                     not null,
    min_players  integer                  not null,
    max_players  integer                  not null,
    updated      timestamp with time zone not null,
    created      timestamp with time zone not null,
    steam_app_id bigint
);

create table steam_app
(
    id                bigint generated by default as identity
        primary key,
    steam_id          bigint                   not null,
    name              text                     not null,
    type              text,
    updated           timestamp with time zone not null,
    created           timestamp with time zone not null,
    version           integer,
    short_description text,
    description       text,
    fill_state        text not null
);

create table steam_app_category
(
    id          bigint generated by default as identity
        primary key,
    steam_id    bigint                   not null,
    description text                     not null,
    updated     timestamp with time zone not null,
    created     timestamp with time zone not null
);

create table steam_app_price
(
    id                bigint generated by default as identity
        primary key,
    steam_app_id      bigint                   not null,
    currency          text                     not null,
    initial           bigint                   not null,
    final             bigint                   not null,
    discount_percent  bigint                   not null,
    initial_formatted text                     not null,
    final_formatted   text                     not null,
    updated           timestamp with time zone not null,
    created           timestamp with time zone not null
);

create table steam_app_steam_app_category
(
    steam_app_id          bigint                   not null,
    steam_app_category_id bigint                   not null,
    updated               timestamp with time zone not null,
    created               timestamp with time zone not null,
    primary key (steam_app_id, steam_app_category_id)
);
