[versions]
reflections = { prefer = "0.10.2" }
postgresql = { prefer = "42.7.7" }
sqlite = { prefer = "3.50.1.0" }
hikari = { prefer = "6.3.0" }
telegram-bot = {prefer = "6.3.0"}

[libraries]
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
sqlite = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
telegram-bot = { module = "com.github.kotlin-telegram-bot:kotlin-telegram-bot", version.ref = "telegram-bot" }


[bundles]
# empty
