spring:
  datasource:
    hikari:
      maximum-pool-size: 1
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    url: ${JDBC_URL}
  application:
    name: TelegramBot
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
